# Generated by Django 2.2.8 on 2019-12-04 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('blo_id', models.AutoField(primary_key=True, serialize=False)),
                ('blo_image1', models.ImageField(max_length=255, upload_to='')),
                ('blo_image2', models.ImageField(max_length=255, upload_to='')),
                ('blo_slxem', models.IntegerField()),
                ('blo_td', models.TextField()),
                ('blo_nd', models.TextField()),
                ('blo_tt', models.TextField()),
                ('blo_tg', models.CharField(max_length=255)),
                ('tag_id', models.IntegerField()),
                ('date_create', models.DateField()),
            ],
            options={
                'db_table': 'tbl_Blog',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('cat_name', models.CharField(max_length=50)),
                ('cat_image', models.ImageField(max_length=255, upload_to='')),
                ('status', models.SmallIntegerField()),
                ('date_create', models.DateField()),
            ],
            options={
                'db_table': 'tbl_Category',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cus_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('date_create', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'tbl_Customer',
            },
        ),
        migrations.CreateModel(
            name='LienHe',
            fields=[
                ('co_id', models.AutoField(primary_key=True, serialize=False)),
                ('co_name', models.CharField(max_length=255)),
                ('co_phone', models.CharField(max_length=10)),
                ('co_email', models.CharField(max_length=255)),
                ('co_adress', models.CharField(max_length=255)),
                ('co_nd', models.TextField()),
            ],
            options={
                'db_table': 'tbl_LienHe',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('total', models.FloatField()),
                ('status', models.SmallIntegerField()),
                ('date_create', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'tbl_Order',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField()),
                ('pro_id', models.IntegerField()),
                ('pro_price', models.IntegerField()),
                ('pro_image', models.IntegerField()),
                ('Quanlity', models.IntegerField()),
                ('status', models.SmallIntegerField()),
                ('date_create', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'tbl_OrderDetail',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pro_id', models.AutoField(primary_key=True, serialize=False)),
                ('pro_name', models.CharField(max_length=50)),
                ('cat_id', models.IntegerField()),
                ('pri_image', models.ImageField(max_length=255, upload_to='')),
                ('pro_price', models.FloatField()),
                ('description', models.TextField()),
                ('status', models.SmallIntegerField()),
                ('date_create', models.DateField()),
            ],
            options={
                'db_table': 'tbl_Product',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=255)),
                ('date_create', models.DateField()),
            ],
            options={
                'db_table': 'tbl_Tag',
            },
        ),
        migrations.CreateModel(
            name='ThuVien',
            fields=[
                ('lib_id', models.AutoField(primary_key=True, serialize=False)),
                ('lib_td', models.TextField()),
                ('lib_nd', models.TextField()),
                ('lib_image', models.ImageField(max_length=255, upload_to='')),
            ],
            options={
                'db_table': 'tbl_ThuVien',
            },
        ),
    ]
