# Generated by Django 3.0.5 on 2020-04-29 08:14

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_categorybl_comment_order_orderdetail_postview_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='overview',
            field=models.TextField(blank=True),
        ),
    ]
